#!/usr/bin/env python3
"""Send a QDII-LOF report generated by the local Rust sidecar."""
import os
import sys
from datetime import date, timedelta
from pathlib import Path
from typing import Any

_SHARED_DIR = Path(__file__).resolve().parents[1] / "_shared"
if _SHARED_DIR.exists():
    sys.path.insert(0, str(_SHARED_DIR))

from ops_common import JsonHttpClient, is_cn_workday, now_shanghai, parse_dt

USE_AKSHARE_CAL = os.environ.get("LOF_USE_AKSHARE_CALENDAR", "0") == "1"
CACHE_MAX_AGE_SECS = int(os.environ.get("LOF_CACHE_MAX_AGE_SECS", "7200"))
RUN_TIMEOUT_SECS = float(os.environ.get("LOF_RUN_TIMEOUT_SECS", "60"))

HTTP = JsonHttpClient(
    [
        os.environ.get("LOF_SIDECAR_URL", "").strip(),
        "http://127.0.0.1:8093",
    ],
    timeout=6,
    post_timeout=RUN_TIMEOUT_SECS,
)


def is_trading_day(check_date=None) -> bool:
    check_date = check_date or date.today()
    if not USE_AKSHARE_CAL:
        return is_cn_workday(check_date, env_var="LOF_HOLIDAY_FILE")
    try:
        import akshare as ak

        trade_dates = ak.tool_trade_date_hist_sina()["trade_date"].astype(str).tolist()
        return str(check_date) in trade_dates
    except Exception:
        return is_cn_workday(check_date, env_var="LOF_HOLIDAY_FILE")


def is_trading_window(now=None) -> bool:
    now = now or now_shanghai()
    hm = now.hour * 60 + now.minute
    return is_trading_day(now.date()) and ((9 * 60 + 30) <= hm <= (11 * 60 + 30) or (13 * 60) <= hm <= (15 * 60))


if not is_trading_window():
    raise SystemExit(0)


def _is_cache_fresh_for_tag(tag: str, finished_at: Any) -> bool:
    finished_local = parse_dt(finished_at)
    if not finished_local:
        return False

    now = now_shanghai()
    if now - finished_local > timedelta(seconds=CACHE_MAX_AGE_SECS):
        return False
    if finished_local.date() != now.date():
        return False

    if "\u5348" in tag:
        return (finished_local.hour, finished_local.minute) >= (13, 0)
    if "\u65e9" in tag:
        return (finished_local.hour, finished_local.minute) >= (9, 30)
    if "\u6536\u76d8" in tag:
        return (finished_local.hour, finished_local.minute) >= (14, 45)
    return True


def load_cached_report(tag: str) -> str:
    data = HTTP.get_json("/api/status", {})
    last_run = data.get("last_run") or {}
    report = (last_run.get("report") or "").strip()
    status = (last_run.get("status") or "").strip()
    if report and status == "ok" and _is_cache_fresh_for_tag(tag, last_run.get("finished_at")):
        return report
    return ""


def run_fresh_report(tag: str) -> tuple[str, str]:
    data = HTTP.post_json("/api/run", {"tag": tag}, default={})
    report = (data.get("report") or "").strip()
    if report:
        return report, ""
    error = data.get("error") or f"refresh failed or timed out after {RUN_TIMEOUT_SECS:g}s"
    return "", str(error)


def main() -> int:
    tag = sys.argv[1] if len(sys.argv) > 1 else "\u65e9\u5e02"

    if not is_trading_day():
        print(f"[INFO] {date.today()} is not a trading day; no QDII report sent.")
        return 0

    report, refresh_error = run_fresh_report(tag)
    if report:
        print(report)
        return 0

    cached = load_cached_report(tag)
    if cached:
        print(f"[WARN] LOF realtime refresh failed, using cached report: {refresh_error}")
        print(cached)
        return 0

    print(f"[WARN] LOF sidecar failed: {refresh_error or 'sidecar empty report'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
